"""committee assignments

Revision ID: 2e6b15b7a104
Revises: 6cd6a286a3ee
Create Date: 2026-07-19 16:33:43.861709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e6b15b7a104'
down_revision: Union[str, None] = '6cd6a286a3ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committee',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('thomas_id', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('chamber', sa.String(length=8), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('source_fetch_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_fetch_id'], ['source_fetch.id'], name=op.f('fk_committee_source_fetch_id_source_fetch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_committee')),
    sa.UniqueConstraint('thomas_id', name=op.f('uq_committee_thomas_id'))
    )
    op.create_table('committee_membership',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('committee_id', sa.BigInteger(), nullable=False),
    sa.Column('figure_id', sa.BigInteger(), nullable=False),
    sa.Column('role_title', sa.String(length=64), nullable=True),
    sa.Column('rank', sa.SmallInteger(), nullable=True),
    sa.Column('party_side', sa.String(length=16), nullable=True),
    sa.Column('source_fetch_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['committee_id'], ['committee.id'], name=op.f('fk_committee_membership_committee_id_committee')),
    sa.ForeignKeyConstraint(['figure_id'], ['figure.id'], name=op.f('fk_committee_membership_figure_id_figure')),
    sa.ForeignKeyConstraint(['source_fetch_id'], ['source_fetch.id'], name=op.f('fk_committee_membership_source_fetch_id_source_fetch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_committee_membership')),
    sa.UniqueConstraint('committee_id', 'figure_id', name='uq_committee_membership_identity')
    )
    op.create_index('ix_committee_membership_figure_id', 'committee_membership', ['figure_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_committee_membership_figure_id', table_name='committee_membership')
    op.drop_table('committee_membership')
    op.drop_table('committee')
    # ### end Alembic commands ###
