"""initial schema

Revision ID: 3c398ebe6a9b
Revises: 
Create Date: 2026-07-18 16:30:59.232709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c398ebe6a9b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector (embedding column + hnsw index) and pg_trgm (trigram GIN index)
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_run',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('adapter', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'failure', name='run_status'), nullable=False),
    sa.Column('records_seen', sa.Integer(), server_default='0', nullable=False),
    sa.Column('records_upserted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_run'))
    )
    op.create_index(op.f('ix_ingestion_run_adapter'), 'ingestion_run', ['adapter'], unique=False)
    op.create_table('source_fetch',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('adapter', sa.String(length=64), nullable=False),
    sa.Column('native_id', sa.String(length=512), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_version', sa.String(length=256), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_fetch')),
    sa.UniqueConstraint('adapter', 'native_id', 'content_hash', name='uq_source_fetch_identity')
    )
    op.create_index(op.f('ix_source_fetch_adapter'), 'source_fetch', ['adapter'], unique=False)
    op.create_table('topic',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('taxonomy', sa.String(length=64), server_default='crs_policy_area', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic')),
    sa.UniqueConstraint('name', name=op.f('uq_topic_name'))
    )
    op.create_table('bill',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('congress', sa.SmallInteger(), nullable=False),
    sa.Column('bill_type', sa.String(length=8), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('policy_area', sa.String(length=128), nullable=True),
    sa.Column('latest_action_date', sa.Date(), nullable=True),
    sa.Column('latest_action_text', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_fetch_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_fetch_id'], ['source_fetch.id'], name=op.f('fk_bill_source_fetch_id_source_fetch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill')),
    sa.UniqueConstraint('congress', 'bill_type', 'number', name='uq_bill_identity')
    )
    op.create_table('figure',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('branch', sa.Enum('legislative', 'executive', 'judicial', name='branch'), nullable=False),
    sa.Column('bioguide_id', sa.String(length=16), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('official_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('source_fetch_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_fetch_id'], ['source_fetch.id'], name=op.f('fk_figure_source_fetch_id_source_fetch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_figure')),
    sa.UniqueConstraint('bioguide_id', name=op.f('uq_figure_bioguide_id')),
    sa.UniqueConstraint('slug', name=op.f('uq_figure_slug'))
    )
    op.create_index(op.f('ix_figure_branch'), 'figure', ['branch'], unique=False)
    op.create_table('source_package',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('adapter', sa.String(length=64), nullable=False),
    sa.Column('package_id', sa.String(length=512), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('statement_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('source_fetch_id', sa.BigInteger(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'ingested', 'failed')", name=op.f('ck_source_package_status_allowed')),
    sa.ForeignKeyConstraint(['source_fetch_id'], ['source_fetch.id'], name=op.f('fk_source_package_source_fetch_id_source_fetch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_package')),
    sa.UniqueConstraint('adapter', 'package_id', name='uq_source_package_identity')
    )
    op.create_index(op.f('ix_source_package_adapter'), 'source_package', ['adapter'], unique=False)
    op.create_index(op.f('ix_source_package_issue_date'), 'source_package', ['issue_date'], unique=False)
    op.create_table('bill_sponsorship',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('bill_id', sa.BigInteger(), nullable=False),
    sa.Column('figure_id', sa.BigInteger(), nullable=False),
    sa.Column('is_original', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sponsored_date', sa.Date(), nullable=True),
    sa.Column('source_fetch_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], name=op.f('fk_bill_sponsorship_bill_id_bill')),
    sa.ForeignKeyConstraint(['figure_id'], ['figure.id'], name=op.f('fk_bill_sponsorship_figure_id_figure')),
    sa.ForeignKeyConstraint(['source_fetch_id'], ['source_fetch.id'], name=op.f('fk_bill_sponsorship_source_fetch_id_source_fetch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill_sponsorship')),
    sa.UniqueConstraint('bill_id', 'figure_id', name='uq_bill_sponsorship_identity')
    )
    op.create_index('ix_bill_sponsorship_figure_id', 'bill_sponsorship', ['figure_id'], unique=False)
    op.create_table('external_id',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('figure_id', sa.BigInteger(), nullable=False),
    sa.Column('id_type', sa.String(length=32), nullable=False),
    sa.Column('id_value', sa.String(length=256), nullable=False),
    sa.Column('source_fetch_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['figure_id'], ['figure.id'], name=op.f('fk_external_id_figure_id_figure')),
    sa.ForeignKeyConstraint(['source_fetch_id'], ['source_fetch.id'], name=op.f('fk_external_id_source_fetch_id_source_fetch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_id')),
    sa.UniqueConstraint('id_type', 'id_value', name='uq_external_id_identity')
    )
    op.create_index('ix_external_id_figure_id', 'external_id', ['figure_id'], unique=False)
    op.create_table('figure_role',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('figure_id', sa.BigInteger(), nullable=False),
    sa.Column('role_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('chamber', sa.Enum('house', 'senate', name='chamber'), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('district', sa.SmallInteger(), nullable=True),
    sa.Column('party', sa.String(length=64), nullable=True),
    sa.Column('is_acting', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_fetch_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['figure_id'], ['figure.id'], name=op.f('fk_figure_role_figure_id_figure')),
    sa.ForeignKeyConstraint(['source_fetch_id'], ['source_fetch.id'], name=op.f('fk_figure_role_source_fetch_id_source_fetch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_figure_role')),
    sa.UniqueConstraint('figure_id', 'role_type', 'start_date', name='uq_figure_role_identity')
    )
    op.create_index('ix_figure_role_figure_id', 'figure_role', ['figure_id'], unique=False)
    op.create_table('finance_summary',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('figure_id', sa.BigInteger(), nullable=False),
    sa.Column('fec_candidate_id', sa.String(length=16), nullable=False),
    sa.Column('cycle', sa.SmallInteger(), nullable=False),
    sa.Column('total_receipts', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_disbursements', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cash_on_hand', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('debts', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('coverage_end_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_fetch_id', sa.BigInteger(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['figure_id'], ['figure.id'], name=op.f('fk_finance_summary_figure_id_figure')),
    sa.ForeignKeyConstraint(['source_fetch_id'], ['source_fetch.id'], name=op.f('fk_finance_summary_source_fetch_id_source_fetch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_summary')),
    sa.UniqueConstraint('figure_id', 'fec_candidate_id', 'cycle', name='uq_finance_summary_identity')
    )
    op.create_index('ix_finance_summary_figure_id', 'finance_summary', ['figure_id'], unique=False)
    op.create_table('roll_call',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('congress', sa.SmallInteger(), nullable=False),
    sa.Column('chamber', sa.Enum('house', 'senate', name='chamber'), nullable=False),
    sa.Column('session', sa.SmallInteger(), nullable=False),
    sa.Column('roll_number', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=128), nullable=True),
    sa.Column('vote_date', sa.Date(), nullable=False),
    sa.Column('bill_id', sa.BigInteger(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_fetch_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], name=op.f('fk_roll_call_bill_id_bill')),
    sa.ForeignKeyConstraint(['source_fetch_id'], ['source_fetch.id'], name=op.f('fk_roll_call_source_fetch_id_source_fetch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roll_call')),
    sa.UniqueConstraint('congress', 'chamber', 'session', 'roll_number', name='uq_roll_call_identity')
    )
    op.create_index(op.f('ix_roll_call_vote_date'), 'roll_call', ['vote_date'], unique=False)
    op.create_table('statement',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('figure_id', sa.BigInteger(), nullable=False),
    sa.Column('utterance_text', sa.Text(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('context_window', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('attribution_method', sa.String(length=64), nullable=True),
    sa.Column('heading', sa.Text(), nullable=True),
    sa.Column('native_id', sa.String(length=512), nullable=False),
    sa.Column('source_fetch_id', sa.BigInteger(), nullable=False),
    sa.Column('source_package_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['figure_id'], ['figure.id'], name=op.f('fk_statement_figure_id_figure')),
    sa.ForeignKeyConstraint(['source_fetch_id'], ['source_fetch.id'], name=op.f('fk_statement_source_fetch_id_source_fetch')),
    sa.ForeignKeyConstraint(['source_package_id'], ['source_package.id'], name=op.f('fk_statement_source_package_id_source_package')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statement')),
    sa.UniqueConstraint('source_type', 'native_id', name='uq_statement_identity')
    )
    op.create_index('ix_statement_figure_id_occurred_on', 'statement', ['figure_id', 'occurred_on'], unique=False)
    op.create_table('statement_chunk',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('statement_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(dim=384), nullable=True),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', chunk_text)", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['statement_id'], ['statement.id'], name=op.f('fk_statement_chunk_statement_id_statement')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statement_chunk')),
    sa.UniqueConstraint('statement_id', 'chunk_index', name='uq_statement_chunk_identity')
    )
    op.create_index('ix_statement_chunk_embedding_hnsw', 'statement_chunk', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_statement_chunk_trgm', 'statement_chunk', ['chunk_text'], unique=False, postgresql_using='gin', postgresql_ops={'chunk_text': 'gin_trgm_ops'})
    op.create_index('ix_statement_chunk_tsv', 'statement_chunk', ['tsv'], unique=False, postgresql_using='gin')
    op.create_table('statement_topic',
    sa.Column('statement_id', sa.BigInteger(), nullable=False),
    sa.Column('topic_id', sa.BigInteger(), nullable=False),
    sa.Column('confidence', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['statement.id'], name=op.f('fk_statement_topic_statement_id_statement')),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], name=op.f('fk_statement_topic_topic_id_topic')),
    sa.PrimaryKeyConstraint('statement_id', 'topic_id', name=op.f('pk_statement_topic'))
    )
    op.create_table('vote_cast',
    sa.Column('roll_call_id', sa.BigInteger(), nullable=False),
    sa.Column('figure_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Enum('yea', 'nay', 'present', 'not_voting', 'other', name='vote_position'), nullable=False),
    sa.Column('position_raw', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['figure_id'], ['figure.id'], name=op.f('fk_vote_cast_figure_id_figure')),
    sa.ForeignKeyConstraint(['roll_call_id'], ['roll_call.id'], name=op.f('fk_vote_cast_roll_call_id_roll_call')),
    sa.PrimaryKeyConstraint('roll_call_id', 'figure_id', name=op.f('pk_vote_cast'))
    )
    op.create_index('ix_vote_cast_figure_id', 'vote_cast', ['figure_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vote_cast_figure_id', table_name='vote_cast')
    op.drop_table('vote_cast')
    op.drop_table('statement_topic')
    op.drop_index('ix_statement_chunk_tsv', table_name='statement_chunk', postgresql_using='gin')
    op.drop_index('ix_statement_chunk_trgm', table_name='statement_chunk', postgresql_using='gin', postgresql_ops={'chunk_text': 'gin_trgm_ops'})
    op.drop_index('ix_statement_chunk_embedding_hnsw', table_name='statement_chunk', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('statement_chunk')
    op.drop_index('ix_statement_figure_id_occurred_on', table_name='statement')
    op.drop_table('statement')
    op.drop_index(op.f('ix_roll_call_vote_date'), table_name='roll_call')
    op.drop_table('roll_call')
    op.drop_index('ix_finance_summary_figure_id', table_name='finance_summary')
    op.drop_table('finance_summary')
    op.drop_index('ix_figure_role_figure_id', table_name='figure_role')
    op.drop_table('figure_role')
    op.drop_index('ix_external_id_figure_id', table_name='external_id')
    op.drop_table('external_id')
    op.drop_index('ix_bill_sponsorship_figure_id', table_name='bill_sponsorship')
    op.drop_table('bill_sponsorship')
    op.drop_index(op.f('ix_source_package_issue_date'), table_name='source_package')
    op.drop_index(op.f('ix_source_package_adapter'), table_name='source_package')
    op.drop_table('source_package')
    op.drop_index(op.f('ix_figure_branch'), table_name='figure')
    op.drop_table('figure')
    op.drop_table('bill')
    op.drop_table('topic')
    op.drop_index(op.f('ix_source_fetch_adapter'), table_name='source_fetch')
    op.drop_table('source_fetch')
    op.drop_index(op.f('ix_ingestion_run_adapter'), table_name='ingestion_run')
    op.drop_table('ingestion_run')
    sa.Enum(name='run_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='branch').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='chamber').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='vote_position').drop(op.get_bind(), checkfirst=True)
    # extensions left in place: they may be shared with other databases' tooling
    # ### end Alembic commands ###
