"""bill sponsor fields

Revision ID: 3c8a4a335578
Revises: b0da713843f2
Create Date: 2026-07-20 00:27:35.665866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c8a4a335578'
down_revision: Union[str, None] = 'b0da713843f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('sponsor_bioguide', sa.String(length=16), nullable=True))
    op.add_column('bill', sa.Column('sponsor_party', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bill', 'sponsor_party')
    op.drop_column('bill', 'sponsor_bioguide')
    # ### end Alembic commands ###
