"""promise tracking

Revision ID: 61c5652a1e88
Revises: c31fc1eafd0d
Create Date: 2026-07-18 23:20:23.981264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61c5652a1e88'
down_revision: Union[str, None] = 'c31fc1eafd0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promise',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('figure_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('made_on', sa.Date(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('statement_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('unassessed', 'in_progress', 'kept', 'partially_kept', 'not_kept', name='promise_status'), server_default='unassessed', nullable=False),
    sa.Column('assessment', sa.Text(), nullable=True),
    sa.Column('assessed_by', sa.String(length=120), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['figure_id'], ['figure.id'], name=op.f('fk_promise_figure_id_figure')),
    sa.ForeignKeyConstraint(['statement_id'], ['statement.id'], name=op.f('fk_promise_statement_id_statement')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promise'))
    )
    op.create_index('ix_promise_figure_id', 'promise', ['figure_id'], unique=False)
    op.create_table('promise_evidence',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('promise_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('statement_id', sa.BigInteger(), nullable=True),
    sa.Column('roll_call_id', sa.BigInteger(), nullable=True),
    sa.Column('bill_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], name=op.f('fk_promise_evidence_bill_id_bill')),
    sa.ForeignKeyConstraint(['promise_id'], ['promise.id'], name=op.f('fk_promise_evidence_promise_id_promise')),
    sa.ForeignKeyConstraint(['roll_call_id'], ['roll_call.id'], name=op.f('fk_promise_evidence_roll_call_id_roll_call')),
    sa.ForeignKeyConstraint(['statement_id'], ['statement.id'], name=op.f('fk_promise_evidence_statement_id_statement')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promise_evidence'))
    )
    op.create_index('ix_promise_evidence_promise_id', 'promise_evidence', ['promise_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_promise_evidence_promise_id', table_name='promise_evidence')
    op.drop_table('promise_evidence')
    op.drop_index('ix_promise_figure_id', table_name='promise')
    op.drop_table('promise')
    # ### end Alembic commands ###
