"""accountability records and disclosure filings

Revision ID: 6cd6a286a3ee
Revises: 61c5652a1e88
Create Date: 2026-07-19 04:21:00.947569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cd6a286a3ee'
down_revision: Union[str, None] = '61c5652a1e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accountability_record',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('figure_id', sa.BigInteger(), nullable=False),
    sa.Column('record_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('docket_number', sa.String(length=100), nullable=True),
    sa.Column('status_note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['figure_id'], ['figure.id'], name=op.f('fk_accountability_record_figure_id_figure')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accountability_record'))
    )
    op.create_index('ix_accountability_record_figure_id', 'accountability_record', ['figure_id'], unique=False)
    op.create_table('disclosure_filing',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('figure_id', sa.BigInteger(), nullable=False),
    sa.Column('doc_id', sa.String(length=32), nullable=False),
    sa.Column('filing_type_code', sa.String(length=8), nullable=False),
    sa.Column('filing_year', sa.SmallInteger(), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_fetch_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['figure_id'], ['figure.id'], name=op.f('fk_disclosure_filing_figure_id_figure')),
    sa.ForeignKeyConstraint(['source_fetch_id'], ['source_fetch.id'], name=op.f('fk_disclosure_filing_source_fetch_id_source_fetch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disclosure_filing')),
    sa.UniqueConstraint('figure_id', 'doc_id', name='uq_disclosure_filing_identity')
    )
    op.create_index('ix_disclosure_filing_figure_id', 'disclosure_filing', ['figure_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_disclosure_filing_figure_id', table_name='disclosure_filing')
    op.drop_table('disclosure_filing')
    op.drop_index('ix_accountability_record_figure_id', table_name='accountability_record')
    op.drop_table('accountability_record')
    # ### end Alembic commands ###
