"""figure stats

Revision ID: b0da713843f2
Revises: 2e6b15b7a104
Create Date: 2026-07-19 17:20:56.120765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0da713843f2'
down_revision: Union[str, None] = '2e6b15b7a104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('figure_stat',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('figure_id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('numerator', sa.Integer(), nullable=True),
    sa.Column('denominator', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['figure_id'], ['figure.id'], name=op.f('fk_figure_stat_figure_id_figure')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_figure_stat')),
    sa.UniqueConstraint('figure_id', 'key', name='uq_figure_stat_identity')
    )
    op.create_index('ix_figure_stat_figure_id', 'figure_stat', ['figure_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_figure_stat_figure_id', table_name='figure_stat')
    op.drop_table('figure_stat')
    # ### end Alembic commands ###
