"""bill summaries and finance sources

Revision ID: c31fc1eafd0d
Revises: 3c398ebe6a9b
Create Date: 2026-07-18 23:04:10.937835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c31fc1eafd0d'
down_revision: Union[str, None] = '3c398ebe6a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_source',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('figure_id', sa.BigInteger(), nullable=False),
    sa.Column('fec_committee_id', sa.String(length=16), nullable=False),
    sa.Column('cycle', sa.SmallInteger(), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('contribution_count', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_fetch_id', sa.BigInteger(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['figure_id'], ['figure.id'], name=op.f('fk_finance_source_figure_id_figure')),
    sa.ForeignKeyConstraint(['source_fetch_id'], ['source_fetch.id'], name=op.f('fk_finance_source_source_fetch_id_source_fetch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_source')),
    sa.UniqueConstraint('figure_id', 'fec_committee_id', 'cycle', 'source_type', 'name', name='uq_finance_source_identity')
    )
    op.create_index('ix_finance_source_figure_id', 'finance_source', ['figure_id'], unique=False)
    op.add_column('bill', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('bill', sa.Column('summary_date', sa.Date(), nullable=True))
    op.add_column('bill', sa.Column('summary_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('finance_summary', sa.Column('individual_itemized', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('finance_summary', sa.Column('individual_unitemized', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('finance_summary', sa.Column('pac_contributions', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('finance_summary', sa.Column('party_contributions', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('finance_summary', sa.Column('candidate_self', sa.Numeric(precision=14, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finance_summary', 'candidate_self')
    op.drop_column('finance_summary', 'party_contributions')
    op.drop_column('finance_summary', 'pac_contributions')
    op.drop_column('finance_summary', 'individual_unitemized')
    op.drop_column('finance_summary', 'individual_itemized')
    op.drop_column('bill', 'summary_checked_at')
    op.drop_column('bill', 'summary_date')
    op.drop_column('bill', 'summary')
    op.drop_index('ix_finance_source_figure_id', table_name='finance_source')
    op.drop_table('finance_source')
    # ### end Alembic commands ###
